---
AWSTemplateFormatVersion: 2010-09-09
Description: Security groups for Kolide Fleet on Fargate
Resources:
  TaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue Kolide-VPC
      GroupDescription: Allow Kolide Fleet task access from VPC
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/16
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      - CidrIp: 10.0.0.0/16
        IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue Kolide-VPC
      GroupDescription: Allow Redis access from Kolide Fleet
      SecurityGroupIngress:
      - SourceSecurityGroupId: !Ref TaskSecurityGroup
        IpProtocol: tcp
        FromPort: 6379
        ToPort: 6379

  AuroraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue Kolide-VPC
      GroupDescription: Allow Aurora MySQL access from Kolide Fleet
      SecurityGroupIngress:
      - SourceSecurityGroupId: !Ref TaskSecurityGroup
        IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306


Outputs:
  TaskSecurityGroup:
    Value: !Ref TaskSecurityGroup
    Export:
      Name: Kolide-TaskSecurityGroup

  RedisSecurityGroup:
    Value: !Ref RedisSecurityGroup
    Export:
      Name: Kolide-RedisSecurityGroup

  AuroraSecurityGroup:
    Value: !Ref AuroraSecurityGroup
    Export:
      Name: Kolide-AuroraSecurityGroup
