---
AWSTemplateFormatVersion: 2010-09-09
Description: Sample security groups for Kolide on Fargate
Resources:
  KolideSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue Kolide-VPC
      GroupDescription: Allow Kolide task access from VPC
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/16
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      - CidrIp: 10.0.0.0/16
        IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue Kolide-VPC
      GroupDescription: Allow Redis access from Kolide
      SecurityGroupIngress:
      - SourceSecurityGroupId: !Ref KolideSecurityGroup
        IpProtocol: tcp
        FromPort: 6379
        ToPort: 6379

  MySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue Kolide-VPC
      GroupDescription: Allow MySQL access from Kolide
      SecurityGroupIngress:
      - SourceSecurityGroupId: !Ref KolideSecurityGroup
        IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306


Outputs:
  RedisSecurityGroup:
    Value: !Ref RedisSecurityGroup
    Export:
      Name: Kolide-RedisSecurityGroup

  KolideSecurityGroup:
    Value: !Ref KolideSecurityGroup
    Export:
      Name: Kolide-SecurityGroup

  MySQLSecurityGroup:
    Value: !Ref MySQLSecurityGroup
    Export:
      Name: Kolide-MySQLSecurityGroup
