---
AWSTemplateFormatVersion: 2010-09-09
Description: Sample ElastiCache Redis cluster for Kolide on Fargate
Resources:
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Redis Subnet Group
      SubnetIds:
        - !ImportValue Kolide-SubnetPriv0
        - !ImportValue Kolide-SubnetPriv1

  Redis:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AtRestEncryptionEnabled: true
      KmsKeyId: !ImportValue Kolide-KMSKey
      AutomaticFailoverEnabled: false
      AutoMinorVersionUpgrade: true
      CacheNodeType: cache.t3.micro
      Engine: redis
      EngineVersion: 5.0.6
      NumCacheClusters: 1
      PreferredMaintenanceWindow: sun:00:00-sun:01:30
      ReplicationGroupDescription: !Sub 'ReplicationGroup for ${AWS::StackName}'
      SecurityGroupIds:
        - !ImportValue Kolide-RedisSecurityGroup
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName


Outputs:
  Redis:
    Value: !GetAtt Redis.PrimaryEndPoint.Address
    Export:
      Name: Kolide-RedisEndpoint
