---
AWSTemplateFormatVersion: 2010-09-09
Description: Kolide Fleet on Fargate
Parameters:
  KolideAuthJWTKey:
    Type: String
    Description: dd if=/dev/urandom bs=24 count=1 status=none | base64
    NoEcho: true


Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AWS::StackName}-Cluster

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}
      RetentionInDays: 30


  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: !Sub ${AWS::StackName}-TaskExecutionPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - kms:Describe*
            - kms:Decrypt
            Resource:
              - Fn::Sub:
                - arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSKey}
                - KMSKey: !ImportValue Kolide-KMSKey
          - Effect: Allow
            Action:
            - kms:ListKeys
            - kms:ListAliases
            Resource: '*'
          - Effect: Allow
            Action:
            - secretsmanager:GetSecretValue
            Resource:
              - !ImportValue Kolide-AuroraClusterPassword
          - Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - logs:Create*
            - logs:Put*
            - ecs:DeregisterContainerInstance
            - ecs:DiscoverPollEndpoint
            - ecs:Poll
            - ecs:RegisterContainerInstance
            - ecs:StartTelemetrySession
            - ecs:UpdateContainerInstancesState
            - ecs:Submit*
            Resource: '*'


## Task definition
  KolideTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: kolide-fargate
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '1024'
      Memory: '2048'

      ContainerDefinitions:
      - Name: https-redirect
        Image: realkinetic/http-to-https
        MemoryReservation: 256
        PortMappings:
        - ContainerPort: 80
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref CloudWatchLogsGroup
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: !Sub ${AWS::StackName}-HTTPS

      - Name: kolide
        Image: kolide/fleet
        Command:
        - '/bin/sh'
        - '-c'
        - 'apk add openssl && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/kolide.key -out /etc/ssl/kolide.crt -subj "/CN=self-signed/" && ln -sf /dev/stdout /tmp/osquery_result && ln -sf /dev/stderr && fleet prepare db && fleet serve'
        MemoryReservation: 256
        PortMappings:
        - ContainerPort: 8080
        Environment:
        - Name: KOLIDE_AUTH_JWT_KEY
          Value: !Ref KolideAuthJWTKey
        - Name: KOLIDE_MYSQL_ADDRESS
          Value:
            Fn::Sub:
              - ${AuroraEndPoint}:3306
              - AuroraEndPoint: !ImportValue Kolide-AuroraClusterEndpoint
        - Name: KOLIDE_MYSQL_DATABASE
          Value: !ImportValue Kolide-AuroraDBName
        - Name: KOLIDE_MYSQL_USERNAME
          Value: !ImportValue Kolide-AuroraClusterUsername
        - Name: KOLIDE_REDIS_ADDRESS
          Value:
            Fn::Sub:
              - ${RedisEndpoint}:6379
              - RedisEndpoint: !ImportValue Kolide-RedisEndpoint
        - Name: KOLIDE_SERVER_TLS
          Value: 'true'
        - Name: KOLIDE_SERVER_TLS_COMPATIBILITY
          Value: 'modern'
        - Name: KOLIDE_SERVER_CERT
          Value: '/etc/ssl/kolide.crt'
        - Name: KOLIDE_SERVER_KEY
          Value: '/etc/ssl/kolide.key'
        Secrets:
        - Name: KOLIDE_MYSQL_PASSWORD
          ValueFrom: !ImportValue Kolide-AuroraClusterPassword
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref CloudWatchLogsGroup
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: !Ref AWS::StackName
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn

# Service
  KolideService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref KolideTaskDefinition
      LaunchType: FARGATE
      PlatformVersion: '1.4.0'
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
          - !ImportValue Kolide-TaskSecurityGroup
          Subnets:
          - !ImportValue Kolide-SubnetPriv0
          - !ImportValue Kolide-SubnetPriv1
      LoadBalancers:
      - ContainerName: https-redirect
        ContainerPort: 80
        TargetGroupArn: !Ref HTTPSRedirectTargetGroup
      - ContainerName: kolide
        ContainerPort: 8080
        TargetGroupArn: !Ref KolideTargetGroup
    DependsOn: KolideLoadBalancerListener

  HTTPSRedirectTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue Kolide-VPC
      Port: 80
      Protocol: TCP
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3

  KolideTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue Kolide-VPC
      Port: 8080
      Protocol: TLS
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3

  HTTPSRedirectLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !ImportValue Kolide-NetworkLoadBalancer
      Port: 80
      Protocol: TCP
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref HTTPSRedirectTargetGroup
  KolideLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !ImportValue Kolide-NetworkLoadBalancer
      Port: 443
      Protocol: TLS
      Certificates:
      - CertificateArn: !ImportValue Kolide-ACMCert
      SslPolicy: ELBSecurityPolicy-FS-1-2-Res-2019-08
      AlpnPolicy:
      - HTTP2Only
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref KolideTargetGroup