---
AWSTemplateFormatVersion: 2010-09-09
Description: Sample ECR repository for Kolide on Fargate
Parameters:
  RepoName:
    Type: String
    Default: kolide-sample
    Description: Name of your ECR repository


Resources:
  ECRRepo:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref RepoName


Outputs:
  ECRLogin:
    Description: Use this to log into your ECR repo
    Value: !Sub 'aws --region ${AWS::Region} ecr get-login-password | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com'
    Export:
      Name: Kolide-ECRLogin

  ECRRepo:
    Description: Full URL for your ECR repo - use this for Docker push and tagging
    Value: !Join [ '', [ !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/', !Ref ECRRepo ] ]
    Export:
      Name: Kolide-ECRRepo
