---
AWSTemplateFormatVersion: 2010-09-09
Description: Sample Aurora cluster for Kolide on Fargate
Parameters:
  AuroraDBName:
    Type: String
    Default: kolideaurorasample
    AllowedPattern: ^[a-z]*$
    ConstraintDescription: Must contain only lower-case alphabetical characters
    MinLength: 1
    MaxLength: 64
    Description: Name of initial database

  AuroraClusterUsername:
    Type: String
    Default: kolideaurorasample
    AllowedPattern: ^[a-z]*$
    ConstraintDescription: Must contain only lower-case alphabetical characters
    MinLength: 1
    MaxLength: 41
    Description: Name of database master user


Resources:
  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Kolide Aurora Subnet Group
      SubnetIds:
        - !ImportValue Kolide-SubnetPriv0
        - !ImportValue Kolide-SubnetPriv1

  AuroraClusterPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: KolideAuroraClusterPassword
      Description: Kolide Aurora Cluster Password
      GenerateSecretString:
        ExcludePunctuation: true
        PasswordLength: 32
      KmsKeyId: !ImportValue Kolide-KMSKey

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    Properties:
      StorageEncrypted: true
      KmsKeyId: !ImportValue Kolide-KMSKey
      Engine: aurora-mysql
      EngineMode: provisioned
      DatabaseName: !Ref AuroraDBName
      MasterUsername: !Ref AuroraClusterUsername
      MasterUserPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref AuroraClusterPassword, '}}' ] ]
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 02:00-04:00
      PreferredMaintenanceWindow: sun:00:00-sun:01:00
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      DBClusterParameterGroupName: default.aurora-mysql5.7
      VpcSecurityGroupIds:
      - !ImportValue Kolide-MySQLSecurityGroup

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-mysql
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.t3.small
      DBParameterGroupName: default.aurora-mysql5.7
      OptionGroupName: "default:aurora-mysql-5-7"
      DBSubnetGroupName: !Ref AuroraSubnetGroup


Outputs:
  AuroraDBName:
    Value: !Ref AuroraDBName
    Export:
      Name: Kolide-AuroraDBName

  AuroraClusterUsername:
    Value: !Ref AuroraClusterUsername
    Export:
      Name: Kolide-AuroraClusterUsername

  AuroraClusterPassword:
    Value: !Ref AuroraClusterPassword
    Export:
      Name: Kolide-AuroraClusterPassword

  AuroraClusterEndpoint:
    Value: !GetAtt AuroraCluster.Endpoint.Address
    Export:
      Name: Kolide-AuroraClusterEndpoint

  AuroraClusterReadEndpoint:
    Value: !GetAtt AuroraCluster.ReadEndpoint.Address
    Export:
      Name: Kolide-AuroraClusterReadEndpoint
