---
AWSTemplateFormatVersion: 2010-09-09
Description: Sample Network Load Balancer for Kolide on Fargate
Resources:
  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: network
      Scheme: internet-facing
      Subnets:
      - !ImportValue Kolide-SubnetPub0
      - !ImportValue Kolide-SubnetPub1
      Tags:
      - Key: Name
        Value: !Sub 'Network Load Balancer for ${AWS::StackName}'


Outputs:
  NetworkLoadBalancer:
    Value: !Ref NetworkLoadBalancer
    Export:
      Name: Kolide-NetworkLoadBalancer

  NetworkLoadBalancerFQDN:
    Description: Use this as a CNAME target for your FQDN
    Value: !GetAtt NetworkLoadBalancer.DNSName
    Export:
      Name: Kolide-NetworkLoadBalancerFQDN